export const CHRONOLOGICAL_MATCH_PAIRINGS = [
  { homeId: "A1", awayId: "A2", group: "A" }, // Match 1
  { homeId: "A3", awayId: "A4", group: "A" }, // Match 2
  { homeId: "B1", awayId: "B2", group: "B" }, // Match 3
  { homeId: "D1", awayId: "D2", group: "D" }, // Match 4
  { homeId: "C3", awayId: "C4", group: "C" }, // Match 5
  { homeId: "D3", awayId: "D4", group: "D" }, // Match 6
  { homeId: "C1", awayId: "C2", group: "C" }, // Match 7
  { homeId: "B3", awayId: "B4", group: "B" }, // Match 8
  { homeId: "E3", awayId: "E4", group: "E" }, // Match 9
  { homeId: "E1", awayId: "E2", group: "E" }, // Match 10
  { homeId: "F1", awayId: "F2", group: "F" }, // Match 11
  { homeId: "F3", awayId: "F4", group: "F" }, // Match 12
  { homeId: "H3", awayId: "H4", group: "H" }, // Match 13
  { homeId: "H1", awayId: "H2", group: "H" }, // Match 14
  { homeId: "G3", awayId: "G4", group: "G" }, // Match 15
  { homeId: "G1", awayId: "G2", group: "G" }, // Match 16
  { homeId: "I1", awayId: "I2", group: "I" }, // Match 17
  { homeId: "I3", awayId: "I4", group: "I" }, // Match 18
  { homeId: "J1", awayId: "J2", group: "J" }, // Match 19
  { homeId: "J3", awayId: "J4", group: "J" }, // Match 20
  { homeId: "L3", awayId: "L4", group: "L" }, // Match 21
  { homeId: "L1", awayId: "L2", group: "L" }, // Match 22
  { homeId: "K1", awayId: "K2", group: "K" }, // Match 23
  { homeId: "K3", awayId: "K4", group: "K" }, // Match 24
  { homeId: "A4", awayId: "A2", group: "A" }, // Match 25
  { homeId: "B4", awayId: "B2", group: "B" }, // Match 26
  { homeId: "B1", awayId: "B3", group: "B" }, // Match 27
  { homeId: "A1", awayId: "A3", group: "A" }, // Match 28
  { homeId: "C1", awayId: "C3", group: "C" }, // Match 29
  { homeId: "C4", awayId: "C2", group: "C" }, // Match 30
  { homeId: "D4", awayId: "D2", group: "D" }, // Match 31
  { homeId: "D1", awayId: "D3", group: "D" }, // Match 32
  { homeId: "E1", awayId: "E3", group: "E" }, // Match 33
  { homeId: "E4", awayId: "E2", group: "E" }, // Match 34
  { homeId: "F1", awayId: "F3", group: "F" }, // Match 35
  { homeId: "F4", awayId: "F2", group: "F" }, // Match 36
  { homeId: "H4", awayId: "H2", group: "H" }, // Match 37
  { homeId: "H1", awayId: "H3", group: "H" }, // Match 38
  { homeId: "G1", awayId: "G3", group: "G" }, // Match 39
  { homeId: "G4", awayId: "G2", group: "G" }, // Match 40
  { homeId: "I4", awayId: "I2", group: "I" }, // Match 41
  { homeId: "I1", awayId: "I3", group: "I" }, // Match 42
  { homeId: "J1", awayId: "J3", group: "J" }, // Match 43
  { homeId: "J4", awayId: "J2", group: "J" }, // Match 44
  { homeId: "L1", awayId: "L3", group: "L" }, // Match 45
  { homeId: "L4", awayId: "L2", group: "L" }, // Match 46
  { homeId: "K1", awayId: "K3", group: "K" }, // Match 47
  { homeId: "K4", awayId: "K2", group: "K" }, // Match 48
  { homeId: "C4", awayId: "C1", group: "C" }, // Match 49
  { homeId: "C2", awayId: "C3", group: "C" }, // Match 50
  { homeId: "B4", awayId: "B1", group: "B" }, // Match 51
  { homeId: "B2", awayId: "B3", group: "B" }, // Match 52
  { homeId: "A4", awayId: "A1", group: "A" }, // Match 53
  { homeId: "A2", awayId: "A3", group: "A" }, // Match 54
  { homeId: "E2", awayId: "E3", group: "E" }, // Match 55
  { homeId: "E4", awayId: "E1", group: "E" }, // Match 56
  { homeId: "F2", awayId: "F3", group: "F" }, // Match 57
  { homeId: "F4", awayId: "F1", group: "F" }, // Match 58
  { homeId: "D4", awayId: "D1", group: "D" }, // Match 59
  { homeId: "D2", awayId: "D3", group: "D" }, // Match 60
  { homeId: "I4", awayId: "I1", group: "I" }, // Match 61
  { homeId: "I2", awayId: "I3", group: "I" }, // Match 62
  { homeId: "G2", awayId: "G3", group: "G" }, // Match 63
  { homeId: "G4", awayId: "G1", group: "G" }, // Match 64
  { homeId: "H2", awayId: "H3", group: "H" }, // Match 65
  { homeId: "H4", awayId: "H1", group: "H" }, // Match 66
  { homeId: "L4", awayId: "L1", group: "L" }, // Match 67
  { homeId: "L2", awayId: "L3", group: "L" }, // Match 68
  { homeId: "J2", awayId: "J3", group: "J" }, // Match 69
  { homeId: "J4", awayId: "J1", group: "J" }, // Match 70
  { homeId: "K4", awayId: "K1", group: "K" }, // Match 71
  { homeId: "K2", awayId: "K3", group: "K" }, // Match 72
];
